//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroikaClothingWeb.Sale_Pages
{


    public partial class SaleHistory
    {

        /// <summary>
        /// hfSelectedReceipt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedReceipt;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlStats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlStats;

        /// <summary>
        /// lblStatOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatOrders;

        /// <summary>
        /// lblStatSpent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatSpent;

        /// <summary>
        /// lblStatLatest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatLatest;

        /// <summary>
        /// gvSale control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSale;

        /// <summary>
        /// pnlNoSaleSelected control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoSaleSelected;

        /// <summary>
        /// pnlSaleDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSaleDetail;

        /// <summary>
        /// lblSelectedReceipt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedReceipt;

        /// <summary>
        /// lblSelectedStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedStatus;

        /// <summary>
        /// lblSelectedDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedDate;

        /// <summary>
        /// lblSelectedPayment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedPayment;

        /// <summary>
        /// lblSelectedCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedCount;

        /// <summary>
        /// lvProductsSold control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ListView lvProductsSold;

        /// <summary>
        /// lblSelectedSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedSubtotal;

        /// <summary>
        /// lblSelectedDelivery control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedDelivery;

        /// <summary>
        /// lblSelectedTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSelectedTotal;
    }
}
