//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroikaClothingWeb.Customer_Pages
{
    public partial class Wishlist
    {
        /// <summary>
        /// rptWishlist control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptWishlist;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// pnlAddToCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAddToCart;

        /// <summary>
        /// btnAtcClose control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAtcClose;

        /// <summary>
        /// imgAtc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAtc;

        /// <summary>
        /// lblAtcName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAtcName;

        /// <summary>
        /// lblAtcPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAtcPrice;

        /// <summary>
        /// ddlAtcColour control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAtcColour;

        /// <summary>
        /// ddlAtcSize control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlAtcSize;

        /// <summary>
        /// txtAtcQuantity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAtcQuantity;

        /// <summary>
        /// hfAtcProductId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfAtcProductId;

        /// <summary>
        /// btnAtcCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAtcCancel;

        /// <summary>
        /// btnAtcAdd control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAtcAdd;
    }
}
