//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TroikaClothingWeb.Controls
{
    public partial class AdminSidebar
    {
        protected global::System.Web.UI.WebControls.Button btnUserList;
        protected global::System.Web.UI.WebControls.Button btnProducts;
        protected global::System.Web.UI.WebControls.Button btnReports;
        protected global::System.Web.UI.WebControls.Button btnProfile;
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
